### ISSUE TITLE
how can i convert bytes type to float

### ISSUE THREAD

**Issue by Haariiii** [Mruchus/dance-sync-analysis#1]
Hello, Mruchus👋
Thank you for sharing the project.

But when I execute the original code, I get the following error.

########## Running Praat script crosscorrelate.praat
OFFSET=b'-\x004\x00.\x005\x004\x009\x008\x000\x009\x004\x009\x003\x004\x001\x008\x007\x001\x004\x00\r\x00\n\x00'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\dance-sync-analysis-main\dance.py", line 250, in <module>
    offset = find_sound_offset(ref_clip_wav, comparison_clip_wav)
  File "C:\Users\User\Desktop\dance-sync-analysis-main\dance.py", line 193, in find_sound_offset
    return abs(float(str(offset)[2:-3]))  #원본
ValueError: could not convert string to float: '-\\x004\\x00.\\x005\\x004\\x009\\x008\\x000\\x009\\x004\\x009\\x003\\x004\\x001\\x008\\x007\\x001\\x004\\x00\\r\\x00\\n\\x'

When I ran the function below, the offset value was returned to b'-\x004\x004\x005\x004\x009\x000\x009\x009\x009\x003\x001\x008\x007\x004\x004\r\x001\x008\n\x00'. 
I think you got this value (b'0.23464366914074475\n') so how can I get this value? Or do you know the value that changes the offset value I got to float?(I'm running in a Windows environment. T.T)

**I should be very grateful to you if you might help me.**

`
def find_sound_offset(ref_wav, comparison_wav):
    # find offset between: ref.wav and clip_name.wav
    start_position = 0
    # command = f"{PRAAT_PATH} --run 'crosscorrelate.praat' {ref_wav} {comparison_wav} {start_position} {SEARCH_INTERVAL}"
    command = f'"{PRAAT_PATH}" --run "crosscorrelate.praat" {ref_wav} {comparison_wav} {start_position} {SEARCH_INTERVAL}'
    # note: code in separate praat file
    offset = subprocess.check_output(command, shell=True)
    # (did some formatting here to get the offset from b'0.23464366914074475\n' to 0.23464366914074475)
    # offset = str(offset.decode('utf-8')).strip("\\")
    # offset = base64.b16decode(offset)
    print(f"OFFSET={offset}")  # b'-\x004\x00.\x005\x004\x009\x008\x000\x009\x004\x009\x003\x004\x001\x008\x007\x001\x004\x00\r\x00\n\x00'
   
    # offset_str = offset.decode('utf-8').strip()
    print(str(offset)[2:-3])
    offset_value = float.fromhex(str(offset)[2:-3])

    print(f"OFFSET={offset_value}")
    
    return abs(float(str(offset)[2:-3]))  #원본
    # return 4.549809493418714  #0.23464366914074475
    # return (offset_str)
`

**Comment by Haariiii** [comment]
i have resolved it, thx!!

**Comment by Haariiii** [comment]
I solved it by returning the str type, thx~!~!
